name: Dev Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echoing
        run: |
          echo "hello"
          echo "hello world"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: secong_echoinh
        run: |
          echo "second hello"
          aws --version
      - name: Wait for user approval
          # if: github.event_name == 'pull_request'
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        with:
          command: 'submit'
  test3:
    runs-on: ubuntu-latest
    needs: test2
    steps:
      - name: secong_echoinh
        run: |
          echo "second hello"
          terraform -v 
    

